/*
 * JavaMASDesktop.java
 *
 * Created on 23 avr. 2013, 12:24:22
 */
package javamas.gui;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author guillaume-monet
 */
public class JavaMASDesktop extends javax.swing.JFrame {

	private ArrayList<JavaMASDesktopComponent> comps = new ArrayList<JavaMASDesktopComponent>();

	/**
	 * Creates new form JavaMASDesktop
	 */
	public JavaMASDesktop() {
		super();
		try {

			UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
		} catch (ClassNotFoundException ex) {
		} catch (InstantiationException ex) {
		} catch (IllegalAccessException ex) {
		} catch (UnsupportedLookAndFeelException ex) {
		}
		initComponents();
		this.setExtendedState(this.getExtendedState()|JFrame.MAXIMIZED_BOTH );
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_tabbedpane = new javax.swing.JTabbedPane();
        main_menu_bar = new javax.swing.JMenuBar();
        main_menu = new javax.swing.JMenu();
        menu_new = new javax.swing.JMenuItem();
        menu_save = new javax.swing.JMenuItem();
        menu_close = new javax.swing.JMenuItem();
        menu_sep = new javax.swing.JPopupMenu.Separator();
        menu_exit = new javax.swing.JMenuItem();
        about_menu = new javax.swing.JMenu();
        menu_about = new javax.swing.JMenuItem();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("javamas2/gui/Bundle"); // NOI18N
        setTitle(bundle.getString("JavaMASDesktop.title")); // NOI18N
        setName("main_frame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        main_menu.setText(bundle.getString("JavaMASDesktop.main_menu.text")); // NOI18N

        menu_new.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menu_new.setText(bundle.getString("JavaMASDesktop.menu_new.text")); // NOI18N
        menu_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_newActionPerformed(evt);
            }
        });
        main_menu.add(menu_new);

        menu_save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menu_save.setText(bundle.getString("JavaMASDesktop.menu_save.text")); // NOI18N
        menu_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_saveActionPerformed(evt);
            }
        });
        main_menu.add(menu_save);

        menu_close.setText(bundle.getString("JavaMASDesktop.menu_close.text")); // NOI18N
        menu_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_closeActionPerformed(evt);
            }
        });
        main_menu.add(menu_close);
        main_menu.add(menu_sep);

        menu_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menu_exit.setText(bundle.getString("JavaMASDesktop.menu_exit.text")); // NOI18N
        menu_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_exitActionPerformed(evt);
            }
        });
        main_menu.add(menu_exit);

        main_menu_bar.add(main_menu);

        about_menu.setText(bundle.getString("JavaMASDesktop.about_menu.text")); // NOI18N
        about_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_menuActionPerformed(evt);
            }
        });

        menu_about.setText(bundle.getString("JavaMASDesktop.menu_about.text")); // NOI18N
        about_menu.add(menu_about);

        main_menu_bar.add(about_menu);

        setJMenuBar(main_menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_tabbedpane, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_tabbedpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void menu_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_newActionPerformed
		JavaMASDesktopComponent comp = new JavaMASDesktopComponent();
		comps.add(comp);
		main_tabbedpane.add("Sim " + comps.size(), comp);
	}//GEN-LAST:event_menu_newActionPerformed

	private void menu_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_saveActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_menu_saveActionPerformed

	private void menu_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_closeActionPerformed
	}//GEN-LAST:event_menu_closeActionPerformed

	private void menu_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_exitActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_menu_exitActionPerformed

	private void about_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_menuActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_about_menuActionPerformed

	private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		// TODO add your handling code here:
	}//GEN-LAST:event_formWindowClosing

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new JavaMASDesktop().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about_menu;
    private javax.swing.JMenu main_menu;
    private javax.swing.JMenuBar main_menu_bar;
    private javax.swing.JTabbedPane main_tabbedpane;
    private javax.swing.JMenuItem menu_about;
    private javax.swing.JMenuItem menu_close;
    private javax.swing.JMenuItem menu_exit;
    private javax.swing.JMenuItem menu_new;
    private javax.swing.JMenuItem menu_save;
    private javax.swing.JPopupMenu.Separator menu_sep;
    // End of variables declaration//GEN-END:variables
}
